jobs:
  buildAUR:
    runs-on: ubuntu-20.04
    steps:
    - uses: Brx86/build-aur-action@yay
      with:
        pkgname: ${{ matrix.repos }}
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ./*/*.pkg.tar.zst
        tag: x86_64
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        repos:
        - code-server
        - debtap
        - flashplugin
        - microsoft-edge-dev-bin
        - optimus-manager-qt
        - pdfsam
        - realesrgan-ncnn-vulkan-bin
        - srmd-ncnn-vulkan-bin
        - sysmontask
        - visual-studio-code-bin
        - yozo-office
        - zy-player-appimage
        - todesk-bin
        - brave-nightly-bin
name: BUILD
'on':
  schedule:
  - cron: 1 */2 * * *
  workflow_dispatch: null
