name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */6 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [w3watch, cant, jzip, zork1, zork2, zork3, atari-adventure, eclipse-subclipse, wallpaper-lightning, squirrelmail, atari-bowling, atari-breakout, atari-combat, atari-space-invaders, mrunit, gtk-gnutella, roundcubemail-plugin-chbox, roundcubemail-plugin-jquery-mobile, roundcubemail-plugin-mobile, eclipse-svnkit, eclipse-dltk-core, eclipse-dltk-javascript, eclipse-antlr-runtime, eclipse-dltk-shelled, eclipse-linuxtools, eclipse-dltk-python, eclipse-antlr4-runtime, eclipse-jsonedit, eclipse-goclipse, adwaita-dark-darose, roundcubemail-plugin-keyboard-shortcuts-ng, refind-theme-tux-git, refind-theme-metro-git, ggmud-svn, libiriverdb, griver, fsv2, vecx-git, lib32-glib, lib32-gtk, qjoypad, qjoypad-svn, qjoypad-panzi-git, yumbootstrap-git, nesasm-git, yum-metadata-parser, libretro-fmsx-git, projectm-git, papu-vst-git, rp2a03-vst-git, sn76489-vst-git, ggmud, bpm-git, kodi-addon-vfs-rar, eduke32-git, voidsw-git, kodi-addon-vfs-rar-git, haruna, rakubrew, synochat, brother-dcpj987n-cups-bin]

      fail-fast: false
      
    runs-on: ubuntu-20.04
    
    steps:
    - uses: zjuyk/build-aur-action@master
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "aur"
        artifacts: "./*/*.xz"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "aur"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

  buildNonAUR:
    strategy:
      matrix:
        PKGBUILDs: [rdm, breeze10]

      fail-fast: false
      
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Non-AUR packages
        id: makepkg
        uses: zjuyk/pkgbuild-action@master
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "aur"
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GITHUB_TOKEN }}
