name: BUILD

on:
  workflow_dispatch:
  schedule:
    - cron:  '1 */2 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [flashplugin,pdfsam,microsoft-edge-dev-bin,debtap,zy-player-appimage,python-requests-html,optimus-manager-qt,yozo-office,visual-studio-code-bin,srmd-ncnn-vulkan-bin,realesrgan-ncnn-vulkan-bin,python-realesrgan,realesrgan-model,code-server,sysmontask,todesk-bin]

      fail-fast: false
      
    runs-on: ubuntu-20.04
    
    steps:
    - uses: Brx86/build-aur-action@yay
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./*/*.pkg.tar.zst"
        token: ${{ secrets.GITHUB_TOKEN }}
