jobs:
  buildAUR:
    runs-on: ubuntu-20.04
    steps:
    - uses: Brx86/build-aur-action@yay
      with:
        pkgname: ${{ matrix.repos }}
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: ./*/*.pkg.tar.zst
        tag: x86_64
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        repos:
        - albert-bin
        - code-server
        - debtap
        - deepin-wine5-stable
        - flashplugin
        - flashplayer-standalone
        - microsoft-edge-dev-bin
        - nomachine
        - optimus-manager-qt
        - pdfsam
        - python-conda
        - python-conda-package-handling
        - qrcp-bin
        - realesrgan-ncnn-vulkan-bin
        - rm-improved
        - srmd-ncnn-vulkan-bin
        - sysmontask
        - todesk-bin
        - visual-studio-code-bin
        - yozo-office
        - zy-player-appimage
name: BUILD
'on':
  repository_dispatch:
    types: build_all_hook
  schedule:
  - cron: 1 */2 * * *
  workflow_dispatch: null
