    name: BUILD-MAKEPKG
    on: workflow_dispatch
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        
        - uses: Brx86/build-aur-action@master
          with:
            repo-name: waifu2x-git

        - uses: ncipollo/release-action@v1.6.1
          with:
            allowUpdates: true
            tag: "out"
            artifacts: "./*/*.zst"
            token: ${{ secrets.GITHUB_TOKEN }}

    - uses: Brx86/update-db-for-repo@master
      with:
        tag: x86_64
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./aya.*"
        token: ${{ secrets.GITHUB_TOKEN }}
