name: BUILD-SINGLE
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: Brx86/build-aur-action@master
      with:
        repo-name: com.caustic3.deepin

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: Brx86/update-db-for-repo@master
      with:
        tag: x86_64
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./aya.*"
        token: ${{ secrets.GITHUB_TOKEN }}