name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */12 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [deepin-wine5,deepin-wine5-i386,deepin-wine-helper,deepin-wine32,deepin-wine-qq,deepin-wine-tim,deepin-wine-wechat,deepin-wine32-tools,deepin-wine5-stable,deepin-wine-plugin,com.qq.tim.spark,com.qq.weixin.spark,wine-tim,com.qq.weixin.deepin,com.qq.weixin.work.deepin,deepin.com.qq.im.light,com.qq.im.deepin,deepin-wine6-stable,deepin-wine-helper-full,com.qq.office.deepin,com.qq.im.deepin,deepin-tim-for-arch,deepin.com.qq.office,electron-qq,flashplugin,freechat-uos,motrix,optimus-manager-qt,ttf-ms-fonts,ttf-ms-win10-zh_cn,ttf-ms-win10-2019ltsc,com.pscs6.deepin,lx-music-desktop-bin,pdfsam,wps-office-cn,wps-office-mime-cn,wps-office-mui-zh-cn,wps-office,wps-office-mime,com.caustic3.deepin,ez-daily,qq2mp,pixiv-dl,pplink-bin,stickempires,octopi,octopi-dev,zoom,paru-bin,discord_arch_electron,todesk-bin,microsoft-edge-dev-bin,7-zip,balena-etcher,microsoft-edge-beta-bin,debtap,etcher-bin,notion-app,ncurses5-compat-libs,woeusb,zy-player-appimage,arduino-beta-bin,python-requests-html]

      fail-fast: false
      
    runs-on: ubuntu-20.04
    
    steps:
    - uses: DuckSoft/build-aur-action@master 
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "aur"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

  buildNonAUR:
    strategy:
      matrix:
        PKGBUILDs: []

      fail-fast: false
      
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Non-AUR packages
        id: makepkg
        uses: zjuyk/pkgbuild-action@master
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "aur"
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GITHUB_TOKEN }}
