name: BUILD

on:
  workflow_dispatch:
  schedule:
    - cron:  '1 */2 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [deepin-wine5,deepin-wine5-stable,deepin-wine-helper,deepin-wine-qq,deepin-wine-tim,com.qq.tim.spark,com.qq.weixin.spark,com.qq.weixin.deepin,com.qq.weixin.work.deepin,com.qq.im.deepin,deepin-wine6-stable,com.qq.office.deepin,com.qq.im.deepin,electron-qq,flashplugin,freechat-uos,ttf-ms-fonts,com.pscs6.deepin,pdfsam,wps-office-cn,wps-office,com.caustic3.deepin,ez-daily,qq2mp,pixiv-dl,pplink-bin,stickempires,zoom,paru-bin,discord_arch_electron,todesk-bin,microsoft-edge-dev-bin,7-zip,microsoft-edge-beta-bin,debtap,etcher-bin,ncurses5-compat-libs,woeusb,zy-player-appimage,arduino-beta-bin,python-requests-html,optimus-manager-qt]

      fail-fast: false
      
    runs-on: ubuntu-20.04
    
    steps:
    - uses: Brx86/build-aur-action@yay
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./*/*.pkg.tar.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

  buildNonAUR:
    strategy:
      matrix:
        PKGBUILDs: [netease-cloud-music,qcef]

      fail-fast: false
      
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build Non-AUR packages
        id: makepkg
        uses: zjuyk/pkgbuild-action@master
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "x86_64"
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GITHUB_TOKEN }}
