name: Sync-aliyun
on:
  workflow_dispatch:
  schedule:
    - cron:  '1 */24 * * *'
  workflow_run:
    workflows: ["BUILD"]
    types: [completed]
  repository_dispatch:
    types: update_ali
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Brx86/update-db-for-repo@ali
      with:
        tag: x86_64
